window.TER_ARGUMENTOS = [
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Financiero",
    "feature": "En Construcción – Entrega Noviembre 2027",
    "advantage": "El precio de hoy es el precio de construcción, no el precio de mercado al momento de la entrega.",
    "benefit": "Comprar ahora significa ingresar al activo antes de que suba. En Lima, los proyectos en etapa de construcción históricamente entregan entre 15-25% de plusvalía al momento de escritura.",
    "speech": "\"Cuando recibas tu departamento en noviembre de 2027, su valor en el mercado ya será mayor al precio que pagas hoy. Estás comprando a precio de costo, no a precio de mercado.\"",
    "profile": "Inversionista",
    "objection": "\"¿Y si el proyecto se demora?\" → TER tiene historial de entrega. La plusvalía opera igual incluso con 3-6 meses de variación."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Financiero",
    "feature": "Entrega en construcción – Cuota inicial fraccionada",
    "advantage": "Permite estructurar el desembolso inicial sin descapitalizarse de golpe.",
    "benefit": "El cliente puede distribuir su cuota inicial en cuotas mensuales durante el periodo de construcción, protegiendo su liquidez.",
    "speech": "\"Puedes ingresar al proyecto con una parte del pie y fraccionar el resto mientras el edificio avanza. No tienes que desembolsar todo de una vez.\"",
    "profile": "Todos",
    "objection": "\"No tengo todo el pie ahora mismo\" → Precisamente por eso conviene entrar en esta etapa."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Financiero",
    "feature": "Exclusividad de stock – Compra temprana",
    "advantage": "Las unidades con mejores atributos (pisos altos, vistas, distribución) se agotan primero.",
    "benefit": "Decidir ahora permite asegurar el departamento con la vista o el piso que el cliente realmente quiere. Después solo quedan las opciones que otros descartaron.",
    "speech": "\"Hoy puedes elegir el piso y la orientación que quieres. Cuando el proyecto esté más avanzado, ya no habrá esa posibilidad.\"",
    "profile": "Todos",
    "objection": "\"Necesito pensarlo\" → Entendible. ¿Cuál unidad te interesa? La reservamos y tienes tiempo para decidir."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Sostenibilidad",
    "feature": "Grado 3 Plus Mivivienda",
    "advantage": "Máximo nivel de certificación estatal en sostenibilidad. Accede al mayor Bono del Buen Pagador disponible.",
    "benefit": "El Estado subsidia parte del crédito Y los recibos de luz y agua bajan hasta 30%. Es ahorro doble: en la cuota mensual del banco y en los servicios del departamento.",
    "speech": "\"Este proyecto tiene el grado más alto de Mivivienda. Eso significa que el Estado te da más bono, tu cuota bancaria es menor, y tu recibo de luz y agua baja hasta 30%. Ahorras desde el primer día.\"",
    "profile": "Todos",
    "objection": "\"¿Qué tan confiable es ese ahorro del 30%?\" → Está certificado por el Estado peruano, no es estimación nuestra."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Sostenibilidad",
    "feature": "Paneles Solares + Grado 3 Plus",
    "advantage": "Generación de energía limpia para áreas comunes. Cuota de mantenimiento 30% más baja que un edificio convencional.",
    "benefit": "El mantenimiento mensual es uno de los costos ocultos que los compradores suelen ignorar. Aquí está calculado y reducido desde el diseño del edificio.",
    "speech": "\"La cuota de mantenimiento en este edificio es aproximadamente 30% menor que en uno convencional, porque los paneles generan energía para ascensores, bombas y luces. Eso es dinero en tu bolsillo todos los meses.\"",
    "profile": "Inversionista",
    "objection": "\"¿Cuánto es la cuota de mantenimiento?\" → Más baja que la competencia gracias a los paneles."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Sostenibilidad",
    "feature": "PTAR – Planta de tratamiento de aguas",
    "advantage": "Reutiliza agua de lavabos y duchas para riego de áreas verdes.",
    "benefit": "Elimina el costo del riego de la Terraza Park. El ahorro se traslada directamente a la cuota de mantenimiento del propietario.",
    "speech": "\"El agua que usas en el lavabo se trata y se reutiliza para regar los jardines. Cero costo de riego. Eso reduce lo que pagas cada mes como propietario.\"",
    "profile": "Todos",
    "objection": "\"¿Eso funciona de verdad?\" → Sí, es tecnología usada en edificios premium de todo el mundo, ya integrada en Lima."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Sostenibilidad",
    "feature": "Certificación EDGE – Banco Mundial",
    "advantage": "Aval internacional que certifica ahorro mínimo del 20% en energía, agua y materiales. BBVA ofrece tasas preferenciales a compradores de proyectos EDGE.",
    "benefit": "No es solo un sello verde. Es un respaldo financiero: el banco te presta a menor tasa porque el activo es más eficiente y mantiene mejor su valor de reventa.",
    "speech": "\"Este edificio tiene certificación EDGE del Banco Mundial. Eso significa que cuando vayas a pedir tu crédito hipotecario en BBVA, puedes acceder a una tasa de interés menor. Tu cuota mensual baja.\"",
    "profile": "Todos",
    "objection": "\"¿Eso aplica a todos los bancos?\" → Por ahora principalmente BBVA, pero la tendencia del mercado va hacia ahí."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Áreas Comunes",
    "feature": "Gimnasio completo con zonas de pesas y cardio",
    "advantage": "Gimnasio equipado con separación funcional de espacios. Disponible a pasos del departamento, sin desplazamiento.",
    "benefit": "Un gimnasio comercial en Lima cuesta entre S/ 150 y S/ 250 por persona al mes. Una familia de dos adultos gasta hasta S/ 500 mensuales, es decir S/ 6,000 al año. Aquí está incluido en la cuota de mantenimiento.",
    "speech": "\"¿Vas al gimnasio? Un gimnasio de barrio te cuesta mínimo S/ 150 al mes. Aquí lo tienes en el edificio, con máquinas modernas, y ya está pagado. Recuperas ese costo todos los meses.\"",
    "profile": "Familia",
    "objection": "\"¿Es un gimnasio básico?\" → Tiene zonas diferenciadas de pesas y cardio, similar a un gimnasio comercial."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Áreas Comunes",
    "feature": "Coworking 100% amoblado + WiFi de alta velocidad",
    "advantage": "Espacio profesional dentro del edificio con infraestructura para videollamadas y recepción de clientes.",
    "benefit": "Alquilar una sala de coworking en Miraflores o San Isidro cuesta entre S/ 300 y S/ 800 al mes. Aquí el propietario tiene ese espacio disponible todos los días sin pagar adicional.",
    "speech": "\"Si trabajas desde casa o recibes clientes, tienes una oficina con WiFi, sala de reuniones y fondo para videollamadas a pasos de tu departamento. No necesitas pagar coworking externo.\"",
    "profile": "Profesional",
    "objection": "\"¿Se puede reservar siempre?\" → La administración del edificio gestiona las reservas para garantizar disponibilidad."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Áreas Comunes",
    "feature": "Sala de Directorio independiente",
    "advantage": "Sala cerrada y privada para reuniones confidenciales o de alto nivel.",
    "benefit": "Permite recibir socios, inversores o clientes en un entorno ejecutivo sin usar el departamento ni pagar alquiler de sala.",
    "speech": "\"¿Tienes reuniones de trabajo importantes? Hay una sala de directorio cerrada, completamente equipada. Puedes traer a tus socios o inversores y proyectar imagen corporativa sin salir del edificio.\"",
    "profile": "Profesional",
    "objection": "\"¿Con cuánta anticipación se reserva?\" → La administración gestiona el calendario de uso."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Áreas Comunes",
    "feature": "Parque Central 200 m² en piso 1",
    "advantage": "Mayor área verde privada de la zona. Exclusiva para residentes.",
    "benefit": "Vivir con un parque privado de 200 m² en Lima es un activo escaso. Eleva el valor percibido del conjunto y la calidad de vida cotidiana, especialmente para familias con niños.",
    "speech": "\"El primer piso no es estacionamiento ni depósito: es un parque privado de 200 metros cuadrados solo para los residentes. Tu hijo juega ahí, tú caminas ahí, y nadie externo puede entrar.\"",
    "profile": "Familia",
    "objection": "\"¿Es seguro para niños?\" → Sí, el perímetro está bajo videovigilancia las 24 horas."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Áreas Comunes",
    "feature": "Terraza Park con árboles naturales y vistas panorámicas",
    "advantage": "Vista panorámica a la ciudad y al mar desde una terraza con vegetación real.",
    "benefit": "En el mercado inmobiliario de Lima, las vistas y los espacios al aire libre son diferenciales que incrementan el valor de reventa y la satisfacción del propietario.",
    "speech": "\"Desde la terraza del edificio tienes vista al mar y a la ciudad, con árboles de verdad. Eso no lo tienes en ningún edificio de la zona en este rango de precio.\"",
    "profile": "Todos",
    "objection": "\"¿Todos los pisos tienen vista?\" → Las unidades altas tienen vistas directas. La terraza es de acceso común para todos los residentes."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Áreas Comunes",
    "feature": "3 Zonas de Parrillas con privacidad entre ellas",
    "advantage": "Diseño que permite dos eventos simultáneos sin interferencia acústica ni visual.",
    "benefit": "El propietario puede hacer reuniones de cualquier tamaño sin preocuparse por desordenar su departamento, sin humo en el interior y sin conflictos con vecinos.",
    "speech": "\"¿Organizas reuniones seguido? Tienes tres zonas de parrilla diseñadas para que dos grupos puedan usarlas al mismo tiempo sin molestarse. Tu departamento se mantiene impecable.\"",
    "profile": "Familia",
    "objection": "\"¿Hay costo por reservar las parrillas?\" → La administración define el reglamento de uso sin cobro adicional al mantenimiento."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Tecnología",
    "feature": "3 Ascensores NIDEC (japoneses) para residentes + núcleo independiente para sótanos",
    "advantage": "Tecnología japonesa. Triple redundancia operativa. Núcleo separado que impide que el personal de entregas acceda a los pisos de departamentos.",
    "benefit": "Dos problemas resueltos a la vez: no hay colas en horas punta y el acceso al edificio está segmentado por tipo de usuario.",
    "speech": "\"Hay tres ascensores solo para residentes. Si uno está en mantenimiento, quedan dos. Las entregas y el personal entran por un ascensor separado que no llega a tu piso. Eso es seguridad real.\"",
    "profile": "Todos",
    "objection": "\"¿Y si se van la luz?\" → Los ascensores NIDEC tienen protocolo de seguridad ante cortes de energía."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Tecnología",
    "feature": "Puertas Smart con cerradura digital",
    "advantage": "Control de acceso sin llave física. Códigos temporales para visitas o personal de limpieza. Alertas en tiempo real al celular.",
    "benefit": "Desde el celular el propietario puede revisar si cerró la puerta, abrir remotamente para una visita o recibir alerta si alguien intenta forzarla. Elimina uno de los miedos más comunes del propietario.",
    "speech": "\"¿Alguna vez saliste de casa preguntándote si cerraste la puerta? Con la cerradura digital lo verificas desde tu celular y la cierras si es necesario. También puedes darle acceso temporal a una persona sin darle una copia de llave.\"",
    "profile": "Todos",
    "objection": "\"¿Y si se queda sin batería?\" → Tiene batería de emergencia y opción de apertura manual como respaldo."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Tecnología",
    "feature": "Control de Voz (Alexa integrado)",
    "advantage": "Centraliza luces, música y dispositivos smart con comandos de voz o escenas programadas.",
    "benefit": "Permite crear rutinas del hogar que ahorran tiempo y dan confort inmediato. Es el tipo de tecnología que el propietario muestra con orgullo a sus visitas.",
    "speech": "\"Llegas con las manos ocupadas y dices 'Alexa, llegué': se encienden las luces, suena tu música y se activa el modo que programaste. Eso no lo tiene el edificio de enfrente.\"",
    "profile": "Todos",
    "objection": "\"¿Y si no me gustan los dispositivos de voz?\" → Las luces también tienen switch físico y control desde el celular. La voz es una opción, no una obligación."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Tecnología",
    "feature": "Luces Inteligentes en sala y comedor",
    "advantage": "Control remoto de encendido/apagado. Simulación de presencia cuando el dpto. está vacío.",
    "benefit": "Función de seguridad activa: si viajas, las luces pueden encenderse y apagarse solas simulando que hay alguien en casa. Disuade intentos de robo.",
    "speech": "\"¿Viajas seguido? Las luces del departamento pueden programarse para simular presencia cuando no estás. Es una herramienta de seguridad que parece solo una función de iluminación.\"",
    "profile": "Todos",
    "objection": "\"¿Eso consume mucha electricidad?\" → La tecnología LED consume hasta 80% menos que la iluminación tradicional."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Tecnología",
    "feature": "Gas Natural integrado desde construcción",
    "advantage": "Red de gas natural instalada. Elimina balones de gas en el interior del departamento.",
    "benefit": "Ahorro de hasta 50% frente al gas de balón. Sin el riesgo de fugas por mala instalación de balones. El suministro es continuo y no hay que recordar cambiar el balón.",
    "speech": "\"Con gas natural integrado ahorras hasta la mitad en gas comparado con el balón, no hay riesgo de fugas por instalaciones deficientes, y nunca te queda sin gas a mitad de una cocción.\"",
    "profile": "Todos",
    "objection": "\"¿Quién contrata el suministro?\" → El comprador gestiona el contrato con el proveedor de gas. El punto de conexión ya está instalado en el departamento."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Diseño",
    "feature": "Diseño mariposa – dormitorios en extremos y sala al centro",
    "advantage": "Máxima privacidad entre habitaciones. Área social integrada y amplia. Alta demanda de inversionistas para alquiler.",
    "benefit": "Para una pareja o familia el diseño da independencia a cada habitante. Para un inversionista es el tipo de distribución más demandada en alquiler por habitaciones o Airbnb.",
    "speech": "\"Los dormitorios están en los extremos del departamento, separados por la sala. Cada habitación tiene su privacidad total. Y si quisieras alquilarlo, este diseño es el más buscado en el mercado.\"",
    "profile": "Inversionista",
    "objection": "\"¿Se siente pequeño?\" → El diseño sin pasadizos innecesarios hace que los metros cuadrados se sientan mayores de lo que mide el plano."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Diseño",
    "feature": "7 departamentos por piso (media densidad)",
    "advantage": "Menos tránsito en pasadizos. Menor espera en ascensores. Mayor privacidad respecto a edificios de alta densidad.",
    "benefit": "La sensación de privacidad en el día a día depende en parte de cuántos vecinos compartes el piso. Con 7 unidades, el edificio se siente exclusivo sin ser boutique.",
    "speech": "\"En edificios de Lima hay pisos con 12 o 14 departamentos. Aquí son 7. Eso significa menos ruido en el pasadizo, menos espera en el ascensor y una sensación de mayor exclusividad.\"",
    "profile": "Familia",
    "objection": "\"¿Es un edificio grande?\" → 216 unidades en total, distribuidas en varios pisos, con densidad por piso controlada."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Diseño",
    "feature": "Monitoreo ambiental – sensores de calidad del aire",
    "advantage": "Sensores que miden la pureza del aire interior en tiempo real.",
    "benefit": "En Lima, la contaminación urbana es un factor de salud relevante. Este sistema permite detectar anomalías antes de que sean un problema para los residentes.",
    "speech": "\"El edificio tiene sensores que monitorean la calidad del aire en tiempo real. Si hay alguna anomalía, el sistema lo detecta antes de que lo notes. Es salud preventiva incluida en el edificio.\"",
    "profile": "Familia",
    "objection": "\"¿Dónde se ven esos datos?\" → A través del sistema de administración del edificio y en el lobby."
  },
  {
    "kind": "project",
    "project": "MARSANO PARK",
    "category": "Diseño",
    "feature": "Fachada con Material Cuadroto hasta piso 6",
    "advantage": "Revestimiento de alta durabilidad. No requiere pintura, resane ni mantenimiento constante. Resistente a humedad, smog y sol.",
    "benefit": "La fachada es el primer indicador del estado de un edificio. Un edificio que no necesita repintarse ahorra costos colectivos y mantiene su apariencia premium por décadas.",
    "speech": "\"La fachada no se pinta. Usa un material que no se decolora con el sol, no se ampolla con la humedad y no se ensucia con el smog. En 10 años el edificio va a verse igual que hoy.\"",
    "profile": "Inversionista",
    "objection": "\"¿Ese material es conocido?\" → Sí, es un revestimiento premium usado en proyectos de alto estándar en Lima."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Financiero",
    "feature": "Entrega Inmediata",
    "advantage": "El cliente deja de pagar alquiler desde el primer día. Cero riesgo constructivo. Activo productivo desde hoy.",
    "benefit": "Un alquiler en Miraflores / Surquillo ronda S/ 1,500 – S/ 2,500 mensuales. Cada mes en arriendo es dinero que no construye patrimonio.",
    "speech": "\"No hay espera. Visitas el departamento hoy, ves exactamente lo que recibes y decides. Desde que firmas, dejas de pagar alquiler.\"",
    "profile": "Inversionista",
    "objection": "\"¿Cómo sé que está bien terminado?\" → Puedes inspeccionarlo tú mismo antes de firmar. Sin sorpresas."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Financiero",
    "feature": "Activo productivo desde el día uno",
    "advantage": "Posibilidad de alquiler inmediato. El departamento puede generar flujo de caja en paralelo al crédito hipotecario.",
    "benefit": "Para el inversionista, la entrega inmediata elimina el periodo muerto entre compra y generación de renta.",
    "speech": "\"Si lo alquilas, el departamento empieza a generar renta desde el primer mes. En muchos casos esa renta cubre parte o toda la cuota del banco. El activo se paga solo.\"",
    "profile": "Inversionista",
    "objection": "\"¿Cuánto se puede alquilar?\" → Depende del piso y metraje. Te mostramos referencias de renta actual en la zona."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Diseño",
    "feature": "157 Departamentos – 5 por piso",
    "advantage": "Media densidad por nivel. Menos tránsito y espera en ascensores que edificios de alta densidad.",
    "benefit": "La privacidad cotidiana depende de cuántos vecinos compartes el piso. Con 5 unidades, el pasadizo es silencioso y el ascensor casi siempre disponible.",
    "speech": "\"En tu piso solo hay 5 departamentos. Eso significa que conoces a tus vecinos, el pasadizo está tranquilo y el ascensor no tiene cola.\"",
    "profile": "Familia",
    "objection": "\"¿Es un edificio grande?\" → 157 unidades en total, bien distribuidas en varios pisos para mantener baja densidad por nivel."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Áreas Comunes",
    "feature": "Gimnasio en Piso 30 con vista panorámica al mar",
    "advantage": "Gimnasio equipado en altura con vista al mar. Única combinación en el portafolio TER.",
    "benefit": "Hacer ejercicio con vista al mar no es un lujo estético: está demostrado que los entornos con vistas naturales reducen el estrés y aumentan la adherencia al entrenamiento. Ahorro de S/ 150-250/mes por persona.",
    "speech": "\"Imagínate haciendo cardio mirando el mar desde el piso 30. Eso no existe en ningún gimnasio comercial de Lima. Y está a pasos de tu departamento, sin salir del edificio.\"",
    "profile": "Familia",
    "objection": "\"¿La vista es real o es solo del edificio?\" → Es desde el mismo piso del gimnasio. Las máquinas están orientadas hacia esa vista."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Áreas Comunes",
    "feature": "Coworking en Piso 30",
    "advantage": "Espacio profesional 100% amoblado con WiFi de alta velocidad, en altura con ambiente diferencial.",
    "benefit": "Trabajar en el piso 30 con vistas a Lima cambia completamente la percepción del espacio. Para un cliente o socio que visita, es una primera impresión poderosa.",
    "speech": "\"Tu oficina está en el piso 30 del edificio donde vives. WiFi de alta velocidad, sala para reuniones, fondo perfecto para videollamadas. Sin costo de coworking externo.\"",
    "profile": "Profesional",
    "objection": "\"¿Se puede reservar para todo el día?\" → La administración del edificio gestiona el calendario de reservas."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Áreas Comunes",
    "feature": "Sala de Directorio en Piso 30",
    "advantage": "Sala cerrada e independiente para reuniones confidenciales o de alto nivel, en un entorno ejecutivo con altura.",
    "benefit": "Recibir a socios o inversores en una sala de directorio en el piso 30 genera una impresión difícil de replicar en otro edificio de este rango de precio.",
    "speech": "\"¿Tienes reuniones donde la primera impresión importa? La sala de directorio está en el piso 30, completamente equipada. Tus socios entran y ya saben que estás a otro nivel.\"",
    "profile": "Profesional",
    "objection": "\"¿Hay costo adicional?\" → No. Está incluido en la cuota de mantenimiento."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Áreas Comunes",
    "feature": "Área de Niños en Piso 30 con pisos amortiguadores",
    "advantage": "Espacio lúdico seguro y videovigilado. Pisos especiales que amortiguan caídas.",
    "benefit": "Los padres pueden trabajar en el coworking del mismo piso mientras sus hijos juegan en un área segura y vigilada. Sin traslados a parques públicos.",
    "speech": "\"Tus hijos juegan en el piso 30 mientras tú trabajas en el coworking del mismo nivel. Todo videovigilado, con pisos que amortizan caídas. Sin salir del edificio.\"",
    "profile": "Familia",
    "objection": "\"¿Qué edad es la recomendada?\" → Está diseñado para niños en edad escolar con supervisión de adultos."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Áreas Comunes",
    "feature": "2 Zonas Lunch cerradas con parrilla en Piso 30",
    "advantage": "Espacios sociales cerrados y privados. Uso simultáneo de dos grupos sin interferencia acústica.",
    "benefit": "La sensación de club privado en altura es el diferencial emocional de MORAR. El propietario puede hacer reuniones sin preocuparse por el desorden de su departamento.",
    "speech": "\"En el piso 30 tienes dos zonas de parrilla cerradas y privadas. Puedes hacer tu reunión y tu vecino hace la suya al mismo tiempo sin que se molesten. Como un club privado.\"",
    "profile": "Familia",
    "objection": "\"¿Se puede reservar con anticipación?\" → Sí, a través de la administración del edificio."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Áreas Comunes",
    "feature": "Terraza Park Piso 34 con árboles naturales y vistas panorámicas",
    "advantage": "Terraza en el último nivel con vegetación real y vista doble: ciudad y mar.",
    "benefit": "La Terraza Park en el piso 34 es el espacio más alto y exclusivo del edificio. Eleva el valor percibido del conjunto y es el tipo de espacio que el propietario muestra con orgullo.",
    "speech": "\"El punto más alto del edificio es tuyo: terraza en el piso 34 con árboles reales y vista al mar y a la ciudad. No es una foto de catálogo, lo ves desde el día que te mudas.\"",
    "profile": "Todos",
    "objection": "\"¿Todos los residentes pueden subir?\" → Sí, es área común de acceso exclusivo para propietarios y sus invitados."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Áreas Comunes",
    "feature": "2 Zonas de Parrillas en Piso 34",
    "advantage": "Parrillas en altura con vista panorámica. Diseño que permite dos eventos simultáneos sin interferencia.",
    "benefit": "Organizar una reunión en el piso 34 con vista al mar es un argumento de estilo de vida que ningún dato técnico puede reemplazar.",
    "speech": "\"Imagínate hacer una parrilla con tus amigos en el piso 34 mirando el mar de Lima. Eso es lo que tienes aquí todos los domingos que quieras.\"",
    "profile": "Familia",
    "objection": "\"¿Hay restricción de horarios?\" → La administración define el reglamento de uso de áreas comunes."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Áreas Comunes",
    "feature": "Pet Zone con estación de lavado en Piso 1",
    "advantage": "Único proyecto del portafolio TER con infraestructura exclusiva para mascotas dentro del edificio.",
    "benefit": "Para dueños de mascotas, este espacio resuelve uno de los problemas más cotidianos: llegar de la calle con el perro sucio. Se lava en el edificio antes de subir al departamento.",
    "speech": "\"¿Tienes mascota? MORAR tiene una zona exclusiva para ellas en el primer piso con estación de lavado. Tu departamento siempre limpio, tu perro siempre cuidado, sin salir del edificio.\"",
    "profile": "Familia",
    "objection": "\"¿Es solo para perros?\" → Está diseñado para mascotas en general. La estación de lavado funciona para cualquier mascota de tamaño doméstico."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Sostenibilidad",
    "feature": "Grado 3 Plus Mivivienda + Paneles Solares + PTAR + EDGE",
    "advantage": "Cuádruple certificación de eficiencia energética e hídrica. Mayor bono estatal disponible + tasa preferencial BBVA.",
    "benefit": "Ahorro doble: en la cuota mensual del banco (bono + tasa) y en los recibos de luz y agua (hasta 30% cada uno). La cuota de mantenimiento también es 30% menor gracias a los paneles.",
    "speech": "\"Este edificio tiene el máximo nivel de eficiencia que certifica el Estado peruano. Eso significa menor cuota bancaria, recibos de luz y agua hasta 30% más bajos, y cuota de mantenimiento reducida. Ahorro desde el primer día.\"",
    "profile": "Todos",
    "objection": "\"¿Eso aplica aunque use crédito hipotecario regular?\" → Sí. El bono reduce el monto del préstamo directamente."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Tecnología",
    "feature": "3 Ascensores NIDEC + Núcleo independiente para sótanos",
    "advantage": "Triple redundancia operativa. Segmentación de accesos: residentes vs. entregas y personal.",
    "benefit": "El ascensor de entregas no llega a los pisos de departamentos. El personal externo nunca circula por el pasadizo donde vives.",
    "speech": "\"Hay tres ascensores solo para residentes. Las entregas entran por un núcleo separado que no llega a tu piso. Tu pasadizo es solo tuyo.\"",
    "profile": "Todos",
    "objection": "\"¿Tres ascensores no es exagerado?\" → Cuando uno está en mantenimiento, quedan dos operativos. Cero interrupciones."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Tecnología",
    "feature": "Lobby de 4.53m de altura",
    "advantage": "Arquitectura de doble altura que genera impacto visual inmediato. Más aire y luz natural.",
    "benefit": "El lobby de MORAR es uno de los más altos del portafolio TER. La primera impresión al llegar a casa o al recibir visitas es de un edificio de categoría superior.",
    "speech": "\"El lobby tiene 4.53 metros de altura. Llegas a casa y lo primero que sientes es espacio y luz. Tus visitas también lo sienten. Eso es lo que diferencia un edificio corriente de uno de categoría.\"",
    "profile": "Todos",
    "objection": "\"¿Eso influye en el valor de reventa?\" → Sí. El lobby es la primera imagen que ve un potencial comprador o inquilino."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Tecnología",
    "feature": "Fachada Quadroto hasta piso 9",
    "advantage": "Revestimiento premium de alta durabilidad. Sin pintura, sin mantenimiento constante, resistente a clima, smog y humedad.",
    "benefit": "Mayor cobertura de fachada Quadroto que Marsano Park (piso 9 vs piso 6). El edificio mantiene su apariencia premium por más años sin costo de repintado.",
    "speech": "\"La fachada llega hasta el noveno piso con material que no se pinta, no se deteriora con la humedad y no acumula smog. En 10 años el edificio va a verse igual que el día de entrega.\"",
    "profile": "Inversionista",
    "objection": "\"¿Ese material resiste los temblores?\" → Es un revestimiento flexible diseñado para climas variables. No se fisura con movimientos menores."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Tecnología",
    "feature": "Gas Natural + Cámaras HD + LED en edificio y departamento",
    "advantage": "Trifecta de eficiencia y seguridad: energía económica, vigilancia total, iluminación de bajo consumo.",
    "benefit": "Tres sistemas integrados desde la construcción que reducen costos operativos y elevan la seguridad desde el primer día.",
    "speech": "\"El edificio se entrega con gas natural, cámaras HD en todos los puntos críticos e iluminación LED de alta eficiencia. Todo integrado, sin que tengas que instalar ni contratar nada extra.\"",
    "profile": "Todos",
    "objection": "\"¿El gas lo contrato yo?\" → Sí, el comprador gestiona el suministro. El punto de conexión ya está instalado."
  },
  {
    "kind": "project",
    "project": "MORAR",
    "category": "Diseño",
    "feature": "Kit de Cocina + Muebles altos y bajos + Vanitorio",
    "advantage": "Departamento entregado listo para vivir: cocina equipada, muebles instalados y baños terminados.",
    "benefit": "Ahorro de S/ 2,500 a S/ 4,000 en equipos de cocina más el costo de carpintería. Sin estrés de buscar proveedores ni coordinar instalaciones post-mudanza.",
    "speech": "\"Llegas con tus maletas y cocinas el mismo día. Encimera, horno y campana ya instalados, muebles de cocina y closets listos, vanitorio en baños. Sin un sol más en instalaciones.\"",
    "profile": "Todos",
    "objection": "\"¿De qué marca son los electrodomésticos?\" → Marca reconocida, modelo sujeto a disponibilidad, siempre en rango de calidad equivalente."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Financiero",
    "feature": "Entrega Inmediata",
    "advantage": "El cliente deja de pagar alquiler desde el primer día. Cero riesgo constructivo. El activo es productivo desde hoy.",
    "benefit": "Un alquiler promedio en Miraflores / Surquillo ronda S/ 1,500 – S/ 2,500 mensuales. Cada mes que el comprador espera en un arriendo es dinero que no va a su patrimonio.",
    "speech": "\"No hay espera. Hoy firmas, en pocas semanas puedes mudarte y dejar de pagarle a un casero. O si quieres alquilarlo, empieza a recibir renta de inmediato.\"",
    "profile": "Inversionista",
    "objection": "\"¿Cómo sé que el departamento está bien terminado?\" → Puedes visitarlo hoy y darle la conformidad tú mismo antes de firmar."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Financiero",
    "feature": "Activo productivo desde el día uno",
    "advantage": "Posibilidad de alquiler inmediato. El departamento puede pagar solo desde el primer mes.",
    "benefit": "Para el inversionista, cada mes de espera es rendimiento perdido. Con entrega inmediata el flujo de caja comienza en paralelo al crédito hipotecario.",
    "speech": "\"Si lo alquilas, el departamento puede generar renta desde el primer mes. En muchos casos esa renta cubre parte o toda la cuota del banco. El activo se paga solo.\"",
    "profile": "Inversionista",
    "objection": "\"¿Cuánto se puede alquilar?\" → Depende del piso y metraje. Podemos mostrarte referencias de renta en la zona."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Diseño",
    "feature": "5 Departamentos por piso – baja densidad",
    "advantage": "Menos vecinos por nivel que la mayoría de edificios comparables en precio.",
    "benefit": "Menos tránsito, menos espera en ascensores, mayor sensación de privacidad. Para el comprador que busca vivir, es calidad de vida. Para el inversionista, es un diferencial de alquiler.",
    "speech": "\"En este edificio hay solo cinco departamentos por piso. La mayoría de edificios en Lima tienen el doble. Eso se traduce en tranquilidad y privacidad real.\"",
    "profile": "Familia",
    "objection": "\"¿Cuántos pisos tiene el edificio?\" → 96 departamentos en total distribuidos en varios niveles."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Áreas Comunes",
    "feature": "Gimnasio equipado en el edificio",
    "advantage": "Acceso a gimnasio sin desplazamiento, incluido en la cuota de mantenimiento.",
    "benefit": "Ahorro de S/ 150 a S/ 250 mensuales por persona en gimnasio comercial.",
    "speech": "\"Tienes gimnasio con máquinas modernas a pasos de tu puerta. Un gimnasio comercial en la zona te costaría mínimo S/ 150 al mes. Aquí ya está incluido.\"",
    "profile": "Familia",
    "objection": "\"¿Está bien equipado?\" → Tiene máquinas modernas para cardio y fuerza, equivalente a un gym de barrio."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Áreas Comunes",
    "feature": "Coworking profesional con WiFi de alta velocidad",
    "advantage": "Espacio de trabajo y videollamadas a pasos del departamento, sin costo adicional.",
    "benefit": "Ahorro de hasta S/ 800 mensuales en coworking externo. Permite recibir clientes con imagen profesional.",
    "speech": "\"Si trabajas remoto o recibes clientes, tienes tu oficina a pasos de tu cama, con WiFi rápido, fondo profesional para videollamadas y sin pagar un sol más.\"",
    "profile": "Profesional",
    "objection": "\"¿Hay sala de reuniones también?\" → Sí, el coworking incluye infraestructura para reuniones y presentaciones."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Áreas Comunes",
    "feature": "2 Locales Comerciales en piso 1",
    "advantage": "Servicios disponibles dentro del perímetro del edificio.",
    "benefit": "El propietario puede acceder a servicios sin usar el carro ni salir de su zona de seguridad. Es comodidad cotidiana que también protege el valor del conjunto.",
    "speech": "\"El edificio tiene dos locales comerciales en el primer piso. Tienes servicios disponibles sin salir del edificio. Eso es comodidad todos los días.\"",
    "profile": "Familia",
    "objection": "\"¿Qué tipo de locales habrá?\" → La inmobiliaria gestiona el perfil de locatarios para que sean servicios útiles para los residentes."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Tecnología",
    "feature": "Puertas Smart + Control de Voz + Luces Inteligentes",
    "advantage": "Sistema smart integrado: cerradura digital, voz y luces inteligentes.",
    "benefit": "Tres tecnologías entregadas como equipamiento de cortesía que elevan la percepción de valor del departamento y lo posicionan como premium en el mercado de alquiler.",
    "speech": "\"El departamento se entrega con cerradura digital, control de voz tipo Alexa y luces inteligentes en sala. Es tecnología de departamento de lujo, entregada desde el primer día.\"",
    "profile": "Inversionista",
    "objection": "\"¿Eso tiene costo adicional?\" → No. Es parte del equipamiento de cortesía incluido en el precio del departamento."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Tecnología",
    "feature": "Cámaras de seguridad en todo el condominio",
    "advantage": "Cobertura total de puntos críticos con grabación HD centralizada en lobby.",
    "benefit": "Ante cualquier incidente, el propietario tiene respaldo visual y legal inmediato. El sistema también disuade incidentes antes de que ocurran.",
    "speech": "\"Cada ingreso, pasadizo y área común está cubierto por cámaras HD que graban las 24 horas. Si algo pasa, hay registro inmediato. Eso protege a tu familia y tu inversión.\"",
    "profile": "Todos",
    "objection": "\"¿Quién tiene acceso a las grabaciones?\" → Solo el personal de seguridad del edificio y propietarios ante incidentes formales."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Tecnología",
    "feature": "Gas Natural integrado",
    "advantage": "Red de gas natural instalada desde construcción. Sin balones de gas en el interior.",
    "benefit": "Ahorro del 50% frente al gas de balón. Sin riesgos de fuga. Suministro continuo.",
    "speech": "\"El gas está integrado desde la construcción. Sin balones, sin riesgo de fugas, y ahorras hasta la mitad en costos de gas comparado con un balón convencional.\"",
    "profile": "Todos",
    "objection": "\"¿Quién contrata el servicio de gas?\" → El comprador realiza el contrato. El punto ya está instalado en el departamento."
  },
  {
    "kind": "project",
    "project": "BOLÍVAR",
    "category": "Diseño",
    "feature": "Diseño mariposa + ambos dormitorios con baño propio",
    "advantage": "Distribución en extremos con baño privado para cada dormitorio. Alta demanda en alquiler y Airbnb.",
    "benefit": "Para el inversionista, un departamento con dos baños independientes se alquila más rápido y a mejor precio. Para el usuario final, elimina la fricción del día a día.",
    "speech": "\"Cada dormitorio tiene su propio baño. Se acabaron las colas por el baño en la mañana. Y si quisieras alquilarlo, este diseño es el que mejor renta tiene en el mercado actualmente.\"",
    "profile": "Inversionista",
    "objection": "\"¿Se ve pequeño con dos baños?\" → El diseño mariposa aprovecha cada metro. Los baños no restan espacio visual a los dormitorios."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Financiero",
    "feature": "En Pre-Venta – Entrega Noviembre 2027",
    "advantage": "Precio de pre-venta: el más bajo del ciclo de vida del proyecto. Mayor plazo para fraccionar la cuota inicial.",
    "benefit": "Pre-venta es la etapa donde la plusvalía potencial es máxima y la barrera de entrada mínima. El cliente que entra hoy compra a precio de costo, no de mercado.",
    "speech": "\"Estás entrando en el momento más ventajoso del proyecto. El precio de hoy es el precio de pre-venta: el más bajo que va a tener este departamento en toda su historia. Cuando se entregue en noviembre de 2027, ya valdrá más.\"",
    "profile": "Inversionista",
    "objection": "\"¿Qué pasa si el mercado baja?\" → El precio de pre-venta ya incorpora un margen de seguridad. Incluso con ajuste de mercado, quien entra primero tiene el mejor precio base."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Financiero",
    "feature": "Mayor plazo para fraccionar la cuota inicial",
    "advantage": "Más meses de fraccionamiento que en etapas más avanzadas del proyecto.",
    "benefit": "El cliente puede estructurar su desembolso inicial en cuotas mensuales manejables durante toda la etapa de construcción, sin descapitalizarse.",
    "speech": "\"En pre-venta tienes el mayor plazo para pagar tu cuota inicial en partes. Eso significa cuotas más pequeñas durante la construcción y un impacto mensual menor en tu flujo de caja.\"",
    "profile": "Todos",
    "objection": "\"¿Cuánto es la cuota mensual aproximada?\" → Depende del precio de la unidad y el plazo acordado. Te calculamos el esquema personalizado."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Financiero",
    "feature": "Prioridad en elección de unidades",
    "advantage": "Acceso al stock completo antes de que se abra al mercado general. Primeros en elegir pisos, vistas y distribuciones.",
    "benefit": "Las mejores unidades (pisos altos, vistas al mar, esquineras) se agotan en las primeras semanas. Pre-venta es la única etapa donde el cliente tiene todo el abanico disponible.",
    "speech": "\"Hoy puedes elegir el piso que quieres, la orientación que prefieres y la distribución que mejor te funciona. Cuando el proyecto esté más avanzado, esas opciones ya no estarán disponibles.\"",
    "profile": "Todos",
    "objection": "\"¿Puedo reservar y luego decidir la unidad?\" → Sí. La reserva asegura el precio; tienes un plazo para confirmar la unidad específica."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Diseño",
    "feature": "168 Departamentos – 6 por piso",
    "advantage": "Media densidad por nivel. Balance entre escala de proyecto y privacidad del residente.",
    "benefit": "6 departamentos por piso es un número que permite privacidad sin el costo premium de un edificio boutique. Menos espera en ascensores que edificios de 10+ unidades por piso.",
    "speech": "\"Hay 6 departamentos en tu piso. No es el hacinamiento de un edificio masivo ni el precio de un boutique. Es el punto justo entre privacidad y precio.\"",
    "profile": "Familia",
    "objection": "\"¿Cuántos pisos tiene?\" → 168 unidades distribuidas en varios niveles con 6 por piso."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Áreas Comunes",
    "feature": "Terraza Park en Piso 30 con árboles naturales y vista al mar y ciudad",
    "advantage": "Terraza en altura con vegetación real y vistas panorámicas dobles. Diferencial de estilo de vida único.",
    "benefit": "Una terraza en el piso 30 con árboles reales y vista al mar es un argumento de calidad de vida que no necesita datos: se experimenta.",
    "speech": "\"La terraza del edificio está en el piso 30 con árboles de verdad y vista al mar y a la ciudad. Ese es el espacio donde vas a terminar el día. No hay nada parecido en este rango de precio en Lima.\"",
    "profile": "Todos",
    "objection": "\"¿Todos los residentes tienen acceso?\" → Sí, es área común exclusiva para propietarios y sus invitados."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Áreas Comunes",
    "feature": "2 Zonas de Parrillas en Piso 30",
    "advantage": "Parrillas en altura con diseño que permite dos reuniones simultáneas sin interferencia acústica.",
    "benefit": "El propietario puede hacer reuniones sociales sin desordenar su departamento, sin humo interior y con vista panorámica.",
    "speech": "\"Dos zonas de parrilla en el piso 30. Puedes hacer tu reunión mientras otro vecino hace la suya sin que se molesten. Y tu departamento se queda impecable.\"",
    "profile": "Familia",
    "objection": "\"¿Hay costo por reservar?\" → No. Está incluido en la cuota de mantenimiento."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Áreas Comunes",
    "feature": "Coworking 100% amoblado + WiFi + Sala de Directorio",
    "advantage": "Ecosistema de trabajo completo dentro del edificio: desde videollamadas hasta reuniones de alto nivel.",
    "benefit": "Para el trabajador remoto o el profesional independiente, TEO 618 elimina la necesidad de pagar coworking externo. Hasta S/ 800/mes de ahorro.",
    "speech": "\"Tienes coworking con WiFi de alta velocidad y sala de directorio privada, todo en tu edificio. Para reuniones con clientes, videollamadas o trabajo concentrado sin salir de casa.\"",
    "profile": "Profesional",
    "objection": "\"¿La sala de directorio tiene proyector?\" → Sí, está habilitada con conexiones para presentaciones."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Sostenibilidad",
    "feature": "Grado 3 Plus + Paneles Solares + PTAR + EDGE",
    "advantage": "Cuádruple certificación de eficiencia. El mayor bono estatal + tasa preferencial BBVA + recibos reducidos hasta 30%.",
    "benefit": "El ahorro combinado en crédito, servicios y mantenimiento durante 10 años supera con creces la diferencia de precio frente a un proyecto no certificado.",
    "speech": "\"Cuatro certificaciones de eficiencia simultáneas: Mivivienda Grado 3 Plus, paneles solares, planta de tratamiento de agua y EDGE del Banco Mundial. El Estado te da más bono, el banco te da mejor tasa, y tus recibos bajan 30%.\"",
    "profile": "Todos",
    "objection": "\"¿Todos los proyectos nuevos tienen esto?\" → No. El Grado 3 Plus es el nivel máximo y no todos los proyectos lo alcanzan ni lo solicitan."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Tecnología",
    "feature": "Sistema Smart: Puertas digitales + Control de Voz + Luces Inteligentes",
    "advantage": "Tres capas de tecnología inteligente entregadas como equipamiento de cortesía. Sin costo adicional.",
    "benefit": "Un departamento con smart home integrado se alquila más rápido, a mejor precio y se percibe como premium. Para el usuario final, es comodidad y seguridad cotidiana.",
    "speech": "\"El departamento se entrega con cerradura digital, control de voz y luces inteligentes en sala ya instalados. Es tecnología de edificio de lujo, incluida en el precio.\"",
    "profile": "Inversionista",
    "objection": "\"¿Qué pasa si no me gusta la tecnología?\" → Todo tiene control manual también. La tecnología es una opción, no una obligación."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Tecnología",
    "feature": "2 Ascensores NIDEC (japoneses)",
    "advantage": "Tecnología japonesa con servicio técnico local en Lima. Ante mantenimiento de uno, siempre queda uno operativo.",
    "benefit": "Los motores NIDEC son silenciosos. Para los departamentos cercanos al núcleo de ascensores, eso marca la diferencia en calidad de vida diaria.",
    "speech": "\"Los ascensores son japoneses, marca NIDEC. Silenciosos, suaves y con servicio técnico local. Si uno está en mantenimiento, el otro sigue operando. Cero interrupciones.\"",
    "profile": "Todos",
    "objection": "\"¿Dos ascensores son suficientes para 168 departamentos?\" → Sí, el cálculo de flujo de personas está diseñado para ese volumen con tiempos de espera mínimos."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Tecnología",
    "feature": "Muro Mass y Tabiquería – aislamiento acústico y térmico",
    "advantage": "Sistema de muros con aislamiento acústico superior entre departamentos y del exterior. También aísla térmicamente.",
    "benefit": "En Lima, el ruido entre vecinos es una de las quejas más comunes en edificios convencionales. El Muro Mass resuelve ese problema desde la construcción, no con parches posteriores.",
    "speech": "\"Los muros de TEO 618 tienen un sistema de aislamiento acústico que reduce drásticamente el ruido entre departamentos. Lo que pasa en el departamento del vecino se queda ahí.\"",
    "profile": "Familia",
    "objection": "\"¿Funciona también para el ruido de la calle?\" → Sí, combinado con las ventanas termoacústicas el aislamiento del exterior es muy efectivo."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Tecnología",
    "feature": "Fachada Cuadroto hasta piso 6 + Sensores de aire",
    "advantage": "Fachada premium sin mantenimiento + monitoreo de calidad del aire interior en tiempo real.",
    "benefit": "Dos características que operan en silencio: la fachada no requiere atención y los sensores detectan anomalías antes de que el residente las note.",
    "speech": "\"La fachada no necesita pintura ni mantenimiento por años. Y el edificio tiene sensores que monitorean la calidad del aire interior. Prevención silenciosa que cuida tu salud y tu inversión.\"",
    "profile": "Todos",
    "objection": "\"¿Los sensores de aire generan algún costo?\" → Son parte del sistema del edificio, administrados por la junta de propietarios."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Tecnología",
    "feature": "Gas Natural + Cámaras HD + 2 Locales Comerciales",
    "advantage": "Servicios básicos resueltos desde el primer día: energía económica, seguridad visual y comercios en planta baja.",
    "benefit": "El propietario no necesita salir del edificio para cubrir necesidades cotidianas. Eso eleva la calidad de vida y el atractivo de alquiler.",
    "speech": "\"Gas natural integrado, cámaras HD en todo el edificio y dos locales comerciales en el primer piso. Tienes lo que necesitas sin usar el carro.\"",
    "profile": "Todos",
    "objection": "\"¿Qué locales van a entrar?\" → La inmobiliaria gestiona el perfil de locatarios para que sean servicios útiles para los residentes."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Diseño",
    "feature": "Diseño mariposa + ambos dormitorios con baño propio",
    "advantage": "Distribución en extremos con baños independientes. Alta demanda en alquiler y Airbnb.",
    "benefit": "El diseño mariposa con dos baños es el más rentable del mercado de alquiler en Lima actualmente. Cada habitación tiene su privacidad total.",
    "speech": "\"Los dormitorios están en los extremos con baño propio cada uno. Para vivir es independencia total. Para alquilar, es el diseño más buscado en el mercado. Ideal para Airbnb.\"",
    "profile": "Inversionista",
    "objection": "\"¿El diseño mariposa hace que los cuartos sean más chicos?\" → No. Elimina pasadizos innecesarios, entonces cada metro cuadrado va a espacios útiles."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Diseño",
    "feature": "Kit de Cocina + Muebles altos y bajos + Vanitorio",
    "advantage": "Departamento entregado listo para vivir. Sin inversión adicional en mobiliario o instalaciones.",
    "benefit": "Ahorro de S/ 2,500 a S/ 4,000 en equipos de cocina más carpintería. Sin coordinación de proveedores post-entrega.",
    "speech": "\"Cocina equipada con encimera, horno y campana. Muebles instalados. Vanitorio en baños. Llegas y vives desde el primer día sin gastar un sol más en instalaciones.\"",
    "profile": "Todos",
    "objection": "\"¿Los muebles son de buena calidad?\" → Melamine de 15mm resistente a humedad, arañazos y temperatura. El mismo estándar en todos los proyectos TER."
  },
  {
    "kind": "project",
    "project": "TEO 618",
    "category": "Diseño",
    "feature": "Lobby de ingreso con arquitectura de impacto visual",
    "advantage": "Diseño de ingreso que genera percepción de valor inmediata para propietario y visitas.",
    "benefit": "El lobby es la primera impresión del edificio. Un lobby de diseño impacta en la velocidad de reventa y en el perfil de inquilino que atrae.",
    "speech": "\"El lobby de TEO 618 está diseñado para causar impacto desde que entras. Tus visitas van a notar la diferencia. Y cuando quieras vender o alquilar, esa primera impresión trabaja a tu favor.\"",
    "profile": "Inversionista",
    "objection": "\"¿Tiene recepción con personal?\" → Sí, hay punto de control de acceso en el lobby."
  },
  {
    "kind": "project",
    "project": "PACÍFICO",
    "category": "Financiero",
    "feature": "En Construcción – Entrega Diciembre 2026",
    "advantage": "Precio de construcción con plusvalía al momento de la entrega.",
    "benefit": "Entrega en diciembre 2026 implica un horizonte corto para quien quiere plusvalía rápida o mudanza próxima.",
    "speech": "\"La entrega es en diciembre de 2026. No es una espera larga, pero sí suficiente para que el valor del departamento suba. Entras a precio de hoy y recibes a precio de mercado futuro.\"",
    "profile": "Inversionista",
    "objection": "\"¿Hay riesgo de demora?\" → TER tiene historial de entrega. La plusvalía opera igualmente."
  },
  {
    "kind": "project",
    "project": "PACÍFICO",
    "category": "Diseño",
    "feature": "Solo 2 departamentos por piso – formato boutique",
    "advantage": "El nivel de privacidad más alto posible dentro de un edificio multifamiliar.",
    "benefit": "Con dos vecinos por piso, el edificio se comporta casi como una casa. Silencio, privacidad y sensación de exclusividad que no se consigue en proyectos de mayor escala.",
    "speech": "\"En tu piso solo hay dos departamentos. Dos vecinos. El nivel de privacidad es prácticamente el de una casa, dentro de un edificio con todas las ventajas de seguridad y servicios.\"",
    "profile": "Familia",
    "objection": "\"¿Por qué tiene tan pocos departamentos?\" → Es un proyecto boutique de 11 unidades total. No es para todo el mundo, es para quien valora la privacidad."
  },
  {
    "kind": "project",
    "project": "PACÍFICO",
    "category": "Sostenibilidad",
    "feature": "Grado 3 Plus + Paneles Solares + PTAR + EDGE",
    "advantage": "Cuádruple certificación de eficiencia. El proyecto más completo en términos de sostenibilidad del portafolio TER.",
    "benefit": "Ahorro en crédito hipotecario (bono + tasa preferencial BBVA), ahorro en luz (30%), ahorro en agua (30%), cuota de mantenimiento menor. El ahorro acumulado en 10 años es significativo.",
    "speech": "\"Este proyecto tiene cuatro certificaciones de eficiencia simultáneas. El Estado te da bono, el banco te da mejor tasa, y los servicios bajan 30%. Comprar aquí es más barato de operar que cualquier otro edificio de la zona.\"",
    "profile": "Todos",
    "objection": "\"¿Esas certificaciones son de verdad o marketing?\" → EDGE la emite el Banco Mundial. Mivivienda la otorga el Estado peruano. Ambas tienen auditoría externa independiente."
  },
  {
    "kind": "project",
    "project": "PACÍFICO",
    "category": "Tecnología",
    "feature": "Ascensor NIDEC (japonés) prácticamente exclusivo",
    "advantage": "Con 11 dptos. y un solo ascensor, la disponibilidad es casi permanente para el residente.",
    "benefit": "En proyectos boutique, el ascensor nunca tiene cola. El propietario llega al lobby y sube de inmediato. Pequeño detalle, gran diferencia en calidad de vida diaria.",
    "speech": "\"Con solo 11 departamentos en el edificio, el ascensor está prácticamente siempre libre para ti. No hay esperas, no hay aglomeraciones. Silencioso y de tecnología japonesa.\"",
    "profile": "Todos",
    "objection": "\"¿Y si el ascensor falla?\" → NIDEC tiene servicio técnico local inmediato y repuestos en Lima."
  },
  {
    "kind": "project",
    "project": "PACÍFICO",
    "category": "Tecnología",
    "feature": "Gas Natural integrado",
    "advantage": "Red instalada desde construcción. Ahorro del 50% frente a balón de gas.",
    "benefit": "Sin interrupciones, sin riesgo de fugas, sin almacenar balones inflamables.",
    "speech": "\"Gas natural desde la construcción. Sin balones en el departamento, sin riesgo de fuga y ahorras hasta la mitad en tu recibo de gas mensual.\"",
    "profile": "Todos",
    "objection": "\"¿Quién contrata el suministro?\" → El comprador. El punto de conexión ya está instalado."
  },
  {
    "kind": "project",
    "project": "PACÍFICO",
    "category": "Tecnología",
    "feature": "Cámaras HD centralizadas en lobby",
    "advantage": "Cobertura total con grabación centralizada. Respaldo legal ante incidentes.",
    "benefit": "En un edificio boutique el sistema de cámaras cubre menos superficie, lo que permite una vigilancia más precisa y efectiva.",
    "speech": "\"En un edificio de 11 departamentos, las cámaras cubren cada rincón con mucha mayor precisión que en un edificio de 200 unidades. Seguridad concentrada.\"",
    "profile": "Familia",
    "objection": "\"¿Quién monitorea las cámaras?\" → Personal de seguridad del edificio y administración."
  },
  {
    "kind": "project",
    "project": "PACÍFICO",
    "category": "Diseño",
    "feature": "Dormitorios con baño incorporado",
    "advantage": "Independencia funcional total para cada habitante. Sin compartir espacios íntimos.",
    "benefit": "Calidad de vida concreta: cada persona del hogar maneja sus tiempos sin depender del otro. También es un diferencial de precio en el mercado de alquiler.",
    "speech": "\"Cada dormitorio tiene su propio baño. No hay que coordinar quién entra primero. Para una pareja o para alquilar por habitaciones, es la distribución más cómoda que existe.\"",
    "profile": "Familia",
    "objection": "\"¿Los baños son completos?\" → Sí, con ducha, inodoro y lavatorio con vanitorio."
  },
  {
    "kind": "project",
    "project": "PACÍFICO",
    "category": "Diseño",
    "feature": "Lobby boutique con diseño eficiente",
    "advantage": "Diseño de ingreso con sensación de exclusividad y privacidad. Prioriza seguridad y fluidez.",
    "benefit": "El ingreso de un edificio es la primera impresión para el propietario, sus visitas y sus inquilinos. Un lobby boutique eleva la percepción de valor del conjunto.",
    "speech": "\"El lobby está diseñado para un edificio de 11 departamentos: íntimo, elegante y seguro. No es el hall de un hotel, es el ingreso de tu hogar.\"",
    "profile": "Todos",
    "objection": "\"¿Tiene recepcionista?\" → La administración define el esquema de seguridad. En proyectos boutique suele ser personal de guardia en horario extendido."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Piso SPC (Sala, Dormitorios, Cocina)",
    "advantage": "Material 100% impermeable, aislante acústico y altamente resistente al desgaste y cambios de temperatura.",
    "benefit": "A diferencia del parquet o laminado convencional, el SPC no se hincha con la humedad. Ante una inundación (filtración de pipa de vecino) el piso es recuperable, no se destruye.",
    "speech": "\"El piso de tu departamento es 100% impermeable. Si hay una filtración, el piso no se arruina. En Lima, con la humedad que tenemos, eso marca la diferencia con los pisos de la competencia.\"",
    "profile": "Todos",
    "objection": "\"¿Se ve igual que el parquet?\" → Sí, tiene la estética de madera con mucha mayor resistencia y cero mantenimiento especial."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Piso Porcelanato 60x60 (Baños, Lavandería, Terraza)",
    "advantage": "Alta resistencia al agua, durabilidad prolongada, fácil limpieza.",
    "benefit": "El porcelanato 60x60 es el estándar de proyectos premium en Lima. Mantiene su apariencia por décadas sin requerir productos especiales para su limpieza.",
    "speech": "\"Los baños y la lavandería tienen porcelanato de 60x60, el mismo que ves en hoteles y edificios de alta gama. Sin manchas, sin deterioro, fácil de limpiar.\"",
    "profile": "Todos",
    "objection": "\"¿Se ve diferente al de la competencia?\" → El tamaño 60x60 da sensación de mayor amplitud. La competencia en este rango suele usar 40x40."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Ventanas PVC doble vidrio termoacústico + oscilobatiente",
    "advantage": "Doble aislamiento: térmico (no entra calor ni frío) y acústico (reduce ruido exterior). Dos tipos de apertura.",
    "benefit": "En Lima el ruido urbano y la humedad son los dos enemigos del confort residencial. Esta ventana resuelve ambos y además tiene apertura tipo europeo que facilita la limpieza.",
    "speech": "\"Las ventanas tienen doble vidrio. El ruido de la calle se queda afuera y la temperatura interior se mantiene estable. Además se abren de dos formas, lo que hace la limpieza muy sencilla.\"",
    "profile": "Todos",
    "objection": "\"¿Cuánto aisla realmente?\" → El doble vidrio reduce entre 30-40 dB el ruido exterior. Diferencia notable respecto a vidrio simple."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Mampara corrediza PVC termoacústica (Terraza)",
    "advantage": "Alta durabilidad, fácil limpieza, aislamiento térmico y acústico, hermeticidad total.",
    "benefit": "Protege el interior del departamento del smog y el polvo de Lima. Extiende el área útil hacia la terraza cuando está abierta.",
    "speech": "\"La mampara de la terraza es termoacústica, igual que las ventanas. Cuando la cierras, el departamento queda hermético: sin polvo, sin smog y sin ruido.\"",
    "profile": "Todos",
    "objection": "\"¿El PVC se decolora con el sol?\" → No. El PVC de calidad tiene protección UV. Mantiene el color por años."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Tablero de Granito en Cocina",
    "advantage": "Alta durabilidad, resistencia al calor, fácil de limpiar.",
    "benefit": "El granito es el material de mesada de mayor vida útil en cocina. Soporta ollas calientes directamente, no se raya con fácilidad y se limpia sin productos especiales.",
    "speech": "\"La mesada de tu cocina es granito. Puedes poner una olla caliente directa sobre ella, se limpia en segundos y dura décadas sin perder apariencia. No encontrarás esto en este rango de precio.\"",
    "profile": "Todos",
    "objection": "\"¿Cuánto mide la mesada?\" → Depende de la tipología. Se entrega en el plano de la cocina."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Kit Cocina: Encimera de gas natural + Horno eléctrico + Campana de recirculación",
    "advantage": "Equipamiento de marca reconocida integrado al diseño. Sin necesidad de fósforos ni balones.",
    "benefit": "El comprador ahorra entre S/ 2,500 y S/ 4,000 en electrodomésticos y mano de obra de instalación. Además evita el estrés de buscar técnicos y el riesgo de que los equipos no encajen en el mueble.",
    "speech": "\"Tu cocina se entrega con encimera, horno y campana ya instalados y alineados con el mueble. Ahorras entre S/ 2,500 y S/ 4,000 en equipos e instalación. Llegas con tus maletas y cocinas.\"",
    "profile": "Todos",
    "objection": "\"¿De qué marca son?\" → Marca reconocida. El modelo exacto puede variar por disponibilidad, siempre dentro de rango de calidad equivalente."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Muebles altos y bajos de cocina en Melamine + Muebles de dormitorios",
    "advantage": "Melamine resistente a arañazos, manchas y alta temperatura. Aprovecha toda la verticalidad de la cocina.",
    "benefit": "El propietario no necesita contratar carpintería ni buscar proveedores después de la mudanza. Maximiza el almacenamiento y la cocina se ve despejada desde el primer día.",
    "speech": "\"La cocina se entrega completamente amoblada: muebles altos y bajos ya instalados. Los closets de los dormitorios también vienen. No tienes que gastar ni un sol más en carpintería.\"",
    "profile": "Todos",
    "objection": "\"¿Puedo cambiar el diseño de los muebles?\" → No, se entregan según el diseño del proyecto. Pero puedes añadir organización interior."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Grifería monocomando importada Serie Lome / Diamond",
    "advantage": "Control preciso de caudal y temperatura. Ahorro de agua del 20-30%.",
    "benefit": "Una grifería monocomando importada certifica que el edificio tiene estándar EDGE. También significa que el cliente no tiene que regular temperatura cada vez que usa la ducha.",
    "speech": "\"La grifería de los baños es importada y monocomando. Regulas agua y temperatura con una palanca, mantienes tu mezcla preferida y ahorras entre 20-30% de agua al mes.\"",
    "profile": "Todos",
    "objection": "\"¿Eso es estándar en este precio?\" → No. La mayoría de proyectos en este rango usa grifería local básica. Esta viene por exigencia de la certificación EDGE."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Vanitorio con espejo en todos los baños",
    "advantage": "Almacenamiento integrado bajo el lavatorio. Oculta tuberías.",
    "benefit": "El baño se ve limpio y moderno desde el primer día. Hay espacio para artículos de aseo sin desorden visible en la encimera.",
    "speech": "\"Los baños tienen vanitorio con espacio de almacenamiento. Las tuberías quedan ocultas. El baño se ve como el de un hotel boutique, no como el de un departamento promedio.\"",
    "profile": "Todos",
    "objection": "\"¿El espejo viene incluido?\" → Sí, está instalado como parte del diseño del baño."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Tomacorrientes mixtos con tierra en todo el departamento",
    "advantage": "La línea a tierra evita descargas eléctricas al cuerpo humano y protege los equipos electrónicos.",
    "benefit": "Es el estándar de seguridad eléctrica básico que muchos edificios antiguos en Lima no tienen. Protege televisores, computadoras y electrodomésticos de picos de corriente.",
    "speech": "\"Todos los tomacorrientes del departamento tienen línea a tierra. Eso significa que tus equipos electrónicos están protegidos de picos de corriente y no hay riesgo de descargas eléctricas.\"",
    "profile": "Todos",
    "objection": "\"¿Todos los edificios tienen eso?\" → No. Los edificios antiguos no. En construcción nueva es obligatorio, pero vale la pena mencionarlo."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Puerta principal con cerradura digital en MDF termolaminado",
    "advantage": "Control de acceso sin llave física. Alta resistencia y fácil mantenimiento.",
    "benefit": "La puerta se entrega lista para uso inteligente: sin llaves que perder, con opción de códigos temporales para visitas y alertas en el celular.",
    "speech": "\"La puerta de entrada ya viene con cerradura digital. Sin llaves que perder, con control desde el celular. El departamento se ve y se comporta como premium desde el primer día que abres la puerta.\"",
    "profile": "Todos",
    "objection": "\"¿Y las puertas interiores?\" → MDF termolaminado con chapas de perilla. Alta resistencia y fácil de limpiar."
  },
  {
    "kind": "finish",
    "project": "Acabados generales",
    "category": "Acabados",
    "feature": "Iluminación LED plafón en todos los ambientes",
    "advantage": "Distribución uniforme de luz, sin sombras marcadas. Bajo consumo energético. Vida útil de 20,000-50,000 horas.",
    "benefit": "El departamento se entrega con toda la iluminación instalada. El propietario no gasta en focos, no instala nada y la temperatura interior no sube porque el LED no genera calor.",
    "speech": "\"Todas las luces ya están instaladas: LED de alta calidad con luz uniforme y sin calor. Una bombilla LED dura entre 10 y 25 años. No tendrás que cambiar un foco en mucho tiempo.\"",
    "profile": "Todos",
    "objection": "\"¿La iluminación es suficiente?\" → Los plafones están calculados por ambiente para cubrir la superficie sin puntos oscuros."
  }
];
